### ISSUE TITLE
Line joining with J removes `//` from comment

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust.vim#78]
Line joining with `J` on line 1 here:

```rust
1:  foo();
2:  // comment
```

Produces incorrect result:

```rust
1: foo() comment
```

**Comment by wsdjeg** [comment]
can not reproduce this issue. what is your vim version?

**Comment by chris-morgan** [comment]
This was a Vim bug that was around for quite some time (it’s supposed to remove the `//` if you join two comment lines, but it was also doing this). It appears to have been fixed by Vim 7.4.1797.

**Comment by bluss** [comment]
It's not fixed yet in this version (debian testing), but I suppose I will find a fixed version soon then.

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 10 2016 03:06:14)
Included patches: 1-1829
```

**Comment by rhysd** [comment]
@bluss I fixed this issue at https://github.com/rust-lang/rust.vim/pull/337. If you're still interested in this, please refer it.

**Comment by bluss** [comment]
Thanks for fixing it!
